it('Checkbox', function() {
  cy.visit('https://qpalette-dev.diasoft.ru/interface/qpalettedocui/documentation-7/development/prime-components/checkbox');
  cy.get('#basic > .p-field-checkbox > .p-element > .p-checkbox > .p-checkbox-box').click();
  cy.get('#basic > .p-field-checkbox > label').should('have.text', 'true');
  cy.get('#basic > .p-field-checkbox > .p-element > .p-checkbox > .p-checkbox-box > .p-checkbox-icon').should('have.class', 'pi-check');
  cy.get('#basic > .p-field-checkbox > .p-element > .p-checkbox > .p-checkbox-box > .p-checkbox-icon').click();
  cy.get('#basic > .p-field-checkbox > label').should('have.text', 'false');
  cy.get('#multiple > :nth-child(2) > .p-element > .p-checkbox > .p-checkbox-box').click();
  cy.get('#multiple > :nth-child(2) > .p-element > .p-checkbox > .p-checkbox-box > .p-checkbox-icon').should('have.class', 'pi-check');
  cy.get('#multiple > :nth-child(3) > .p-element > .p-checkbox > .p-checkbox-box').click();
  cy.get('#multiple > :nth-child(3) > .p-element > .p-checkbox > .p-checkbox-box > .p-checkbox-icon').should('have.class', 'pi-check');
  cy.get('#multiple > :nth-child(4) > .p-element > .p-checkbox > .p-checkbox-box').click();
  cy.get('#multiple > :nth-child(4) > .p-element > .p-checkbox > .p-checkbox-box > .p-checkbox-icon').should('have.class', 'pi-check');
  cy.get('#multiple > :nth-child(5) > .p-element > .p-checkbox > .p-checkbox-box').click();
  cy.get('#multiple > :nth-child(5) > .p-element > .p-checkbox > .p-checkbox-box > .p-checkbox-icon').should('have.class', 'pi-check');
  cy.get('#dynamic > :nth-child(2) > .p-element > .p-checkbox > .p-checkbox-box').click();
  cy.get('#dynamic > :nth-child(2) > .p-element > .p-checkbox > .p-checkbox-box > .p-checkbox-icon').should('have.class', 'pi-check');
  cy.get('#dynamic > :nth-child(3) > .p-element > .p-checkbox > .p-checkbox-box').click();
  cy.get('#dynamic > :nth-child(3) > .p-element > .p-checkbox > .p-checkbox-box > .p-checkbox-icon').should('have.class', 'pi-check');
  cy.get('#dynamic > :nth-child(4) > .p-element > .p-checkbox > .p-checkbox-box').click();
  cy.get('#dynamic > :nth-child(4) > .p-element > .p-checkbox > .p-checkbox-box').click();
  cy.get('#dynamic > :nth-child(4) > label').click();
  cy.get('#dynamic > :nth-child(4) > .p-element > .p-checkbox > .p-checkbox-box').click();
  cy.get('#dynamic > :nth-child(4) > .p-element > .p-checkbox > .p-checkbox-box > .p-checkbox-icon').should('have.class', 'pi-check');
});