it('Chips', function() {
  cy.visit('https://qpalette-dev.diasoft.ru/interface/qpalettedocui/documentation-2/development/prime-components/chips');
  cy.get('#basic > .p-grid > .p-col-4 > .p-element > .p-chips > .p-inputtext > .p-chips-input-token').click();
  cy.get('#basic > .p-grid > .p-col-4 > .p-element > .p-chips > .p-inputtext > .p-chips-input-token > input').clear();
  cy.get('#basic > .p-grid > .p-col-4 > .p-element > .p-chips > .p-inputtext > .p-chips-input-token > input').type('Basic1{enter}');
  cy.get('#basic > .p-grid > .p-col-4 > .p-element > .p-chips > .p-inputtext > .p-chips-input-token > input').type('Basic2{enter}');
  cy.get('#basic > .p-grid > .p-col-4 > .p-element > .p-chips > .p-inputtext > .p-chips-input-token > input').type('Basic3{enter}');
  cy.get(':nth-child(1) > .p-chips-token-label').should('have.text', 'Basic1');
  cy.get(':nth-child(2) > .p-chips-token-label').should('have.text', 'Basic2');
  cy.get(':nth-child(3) > .p-chips-token-label').should('have.text', 'Basic3');
  cy.get(':nth-child(3) > .p-chips-token-icon').click();
  cy.get('#commaSeparator > .p-grid > .p-col-4 > .p-element > .p-chips > .p-inputtext > .p-chips-input-token').click();
  cy.get('#commaSeparator > .p-grid > .p-col-4 > .p-element > .p-chips > .p-inputtext > .p-chips-input-token > input').clear();
  cy.get('#commaSeparator > .p-grid > .p-col-4 > .p-element > .p-chips > .p-inputtext > .p-chips-input-token > input').type('Comma1{,}');
  cy.get('#commaSeparator > .p-grid > .p-col-4 > .p-element > .p-chips > .p-inputtext > .p-chips-input-token > input').type('Comma2{,}');
  cy.get('#commaSeparator > .p-grid > .p-col-4 > .p-element > .p-chips > .p-inputtext > .p-chips-input-token > input').type('Comma3{,}');
  cy.get('#commaSeparator > .p-grid > .p-col-4 > .p-element > .p-chips > .p-inputtext > :nth-child(1) > .p-chips-token-label').should('have.text', 'Comma1');
  cy.get('#commaSeparator > .p-grid > .p-col-4 > .p-element > .p-chips > .p-inputtext > :nth-child(2) > .p-chips-token-label').should('have.text', 'Comma2');
  cy.get(':nth-child(3) > .p-chips-token-label').should('have.text', 'Comma3');
  cy.get(':nth-child(3) > .p-chips-token-icon').click();
  cy.get('#template > .p-grid > .p-col-4 > .p-element > .p-chips > .p-inputtext > .p-chips-input-token > input').clear('T');
  cy.get('#template > .p-grid > .p-col-4 > .p-element > .p-chips > .p-inputtext > .p-chips-input-token > input').type('Template1{enter}');
  cy.get('#template > .p-grid > .p-col-4 > .p-element > .p-chips > .p-inputtext > .p-chips-input-token > input').type('Template2{enter}');
  cy.get('#template > .p-grid > .p-col-4 > .p-element > .p-chips > .p-inputtext > :nth-child(1)').should('have.text', ' Template1 - (active) ');
  cy.get('#template > .p-grid > .p-col-4 > .p-element > .p-chips > .p-inputtext > :nth-child(2)').should('have.text', ' Template2 - (active) ');
  cy.get('#template > .p-grid > .p-col-4 > .p-element > .p-chips > .p-inputtext > :nth-child(2) > .p-chips-token-icon').click();
  cy.get('.pi-user').should('have.class', 'pi-user');
});