      it('Test_localization', () => {
        cy.visit("https://qpalette-dev.diasoft.ru/interface/qpalettedocui/documentation-1/releases")
        cy.get('.q-tabs__actions-item > :nth-child(2)').click()
        cy.contains('English').click()
        cy.get('.q-side-dialog__header-title').should('contain','Settings')
        cy.get('.p-tabview-title').should('contain','Main')
        cy.get(':nth-child(1) > .q-settings__item-label').should('contain','Language')
        cy.get(':nth-child(2) > .q-settings__item-label').should('contain','Scale')
        cy.get(':nth-child(3) > .q-settings__item-label').should('contain','Color scheme')
        cy.get(':nth-child(4) > .q-settings__item-label').should('contain','Theme')
        cy.get(':nth-child(5) > .q-settings__item-label').should('contain','Tabs saving mode')
        cy.contains('Русский').click()
        cy.get('.q-side-dialog__header-title').should('contain','Настройки')
        cy.get('.p-tabview-title').should('contain','Основное')
        cy.get(':nth-child(1) > .q-settings__item-label').should('contain','Язык')
        cy.get(':nth-child(2) > .q-settings__item-label').should('contain','Масштаб')
        cy.get(':nth-child(3) > .q-settings__item-label').should('contain','Цветовая схема')
        cy.get(':nth-child(4) > .q-settings__item-label').should('contain','Тема')
        cy.get(':nth-child(5) > .q-settings__item-label').should('contain','Вкладки')
      })