/* ==== Test Created with Cypress Studio ==== */
it('Prime_filters', function() {
  /* ==== Generated with Cypress Studio ==== */
  cy.visit('https://qpalette-dev.diasoft.ru/interface/qpalettedocui/documentation-1/development/templates/table-prime-filters');
  cy.get('.q-filter__label > input').clear('J');
  cy.get('.q-filter__label > input').type('James{enter}');
  cy.get('#pr_id_1-table > .p-element > .ng-star-inserted > :nth-child(1)').should('have.text', ' James Butt ');
  cy.get('[label="Глобальный фильтр"] > .q-filter__wrapper > .q-filter__label > .q-filter__close > q-icon > .pi').click();
  cy.get('.q-filter__label > input').clear('E');
  cy.get('.q-filter__label > input').type('Egypt');
  cy.get(':nth-child(1) > :nth-child(2) > .image-text').should('have.text', 'Egypt');
  cy.get('.q-filter__label > input').clear('I');
  cy.get('.q-filter__label > input').type('Ioni');
  cy.get(':nth-child(1) > :nth-child(3) > .image-text').should('have.text', 'Ioni Bowcher');
  cy.get('[label="Глобальный фильтр"] > .q-filter__wrapper > .q-filter__label > .q-filter__close > q-icon > .pi').click();
  cy.get('.q-filter__label > input').clear('n');
  cy.get('.q-filter__label > input').type('new');
  cy.get(':nth-child(1) > :nth-child(4) > .customer-badge').should('have.text', 'new');
  cy.get(':nth-child(2) > :nth-child(4) > .customer-badge').should('have.text', 'renewal');
  cy.get('[label="Глобальный фильтр"] > .q-filter__wrapper > .q-filter__label > .q-filter__close > q-icon > .pi').click();
  cy.get('p-columnfilter.ng-tns-c112-5 > .p-column-filter > .p-fluid > q-filter-wrapper.ng-star-inserted > .q-filter__wrapper > .q-filter__label > .p-inputwrapper > .p-multiselect > .p-element > .p-multiselect-label').click();
  //cy.get('.p-multiselect > :nth-child(1) > .ng-tns-c119-9').click();
  cy.get(':nth-child(1) > .p-ripple > .ng-star-inserted').click();
  cy.get('.p-multiselect > :nth-child(1) > .ng-tns-c119-9').click();
  cy.get('.p-paginator-bottom').click();
  cy.get('#pr_id_1-table > .p-element > .ng-star-inserted > :nth-child(1)').should('have.text', ' James Butt ');
  cy.get('p-columnfilter.ng-tns-c112-5 > .p-column-filter > .p-fluid > q-filter-wrapper.ng-star-inserted > .q-filter__wrapper > .q-filter__label > .q-filter__close > q-icon > .pi').click();
  cy.get('p-columnfilter.ng-tns-c112-6 > .p-column-filter > .p-fluid > q-filter-wrapper.ng-star-inserted > .q-filter__wrapper > .q-filter__label > .p-element > .p-dropdown > .p-dropdown-label').click();
  cy.get('.p-hidden-accessible > .ng-tns-c83-10').click();
  cy.get(':nth-child(3) > .p-ripple > .ng-star-inserted').click();
  cy.get('.p-hidden-accessible > .ng-tns-c83-10').click();
  cy.get(':nth-child(1) > :nth-child(2) > .image-text').should('have.text', 'Australia');
  cy.get('p-columnfilter.ng-tns-c112-6 > .p-column-filter > .p-fluid > q-filter-wrapper.ng-star-inserted > .q-filter__wrapper > .q-filter__label > .q-filter__close > q-icon > .pi').click();
  cy.get('p-columnfilter.ng-tns-c112-7 > .p-column-filter > .p-fluid > q-filter-wrapper.ng-star-inserted > .q-filter__wrapper > .q-filter__label > span[_ngcontent-bpk-c58=""]').click();
  cy.get('.p-hidden-accessible > .ng-tns-c119-11').click();
  cy.get('p-columnfilter.ng-tns-c112-7 > .p-column-filter > .p-fluid > q-filter-wrapper.ng-star-inserted > .q-filter__wrapper > .q-filter__label > .p-inputwrapper > .p-multiselect > .p-element > .p-multiselect-label').click();
  cy.get('.p-multiselect > :nth-child(1) > .ng-tns-c119-11').click();
  cy.get(':nth-child(2) > .p-ripple > .ng-star-inserted').click();
  cy.get('.p-multiselect > :nth-child(1) > .ng-tns-c119-11').click();
  cy.get(':nth-child(1) > :nth-child(3) > .image-text').should('have.text', 'Anna Fali');
  cy.get('p-columnfilter.ng-tns-c112-7 > .p-column-filter > .p-fluid > q-filter-wrapper.ng-star-inserted > .q-filter__wrapper > .q-filter__label > .q-filter__close > q-icon > .pi').click();
  cy.get('p-columnfilter.ng-tns-c112-8 > .p-column-filter > .p-fluid > q-filter-wrapper.ng-star-inserted > .q-filter__wrapper > .q-filter__label > .p-element > .p-dropdown > .p-dropdown-label').click();
  cy.get('.p-hidden-accessible > .ng-tns-c83-12').click();
  cy.get(':nth-child(4) > .p-ripple > .ng-star-inserted').click();
  cy.get('.p-hidden-accessible > .ng-tns-c83-12').click();
  cy.get(':nth-child(1) > :nth-child(4) > .customer-badge').should('have.text', 'negotiation');
  cy.get('.q-flex > .p-button-icon-only > q-icon > .pi').click();
  cy.get('.p-button-outlined').click();
  cy.get('.q-header > .q-flex > :nth-child(1)').click();
  /* ==== End Cypress Studio ==== */
});